### ISSUE TITLE
Method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by jaimeagudo** [evollu/react-native-fcm#470]
What version of RN and react-native-fcm are you running?
```
  "react-native": "0.47.0-rc.4",
 "react-native-fcm": "7.2.0",
```

What device are you using? (e.g iOS9 emulator, Android 6 device)?

> Android 6 emulator, not compiling

Advanced:
Have you tried adding break point in native handlers to see if message gets delivered?
No
can share a project with issue?
No
```
:react-native-fcm:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/jaime/Github/ROC/RocNativeProject/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingPackage.java:26: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-fcm:compileReleaseJavaWithJavac FAILED
```

**Comment by povloid** [comment]
some problem too

**Comment by pedrogarciyalopez** [comment]
someone solve the problem?

**Comment by PeterEmanuel** [comment]
+1 after updating to 0.47 with the few packages that I use, cm-rn-document-picker, rn-audio-toolkit, 
After removed the document-picker (which I was not yet importing) I got it with the audio-toolkit.

**Comment by asgvard** [comment]
Corresponds to a breaking change:
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

method ```createJSModules``` is no longer needed I guess?

**Comment by asgvard** [comment]
Seems to be fixed here:
https://github.com/evollu/react-native-fcm/commit/4c49ca7e4d3d9b2b2c323f8dbe631789e6bd457a

Try v8.0.0 of FCM

**Comment by Awadhesh31** [comment]
run react-native link and react-native upgrade inside you project then run
react-native run-android / ios

**Comment by Awadhesh31** [comment]
run react-native link and react-native upgrade inside you project then run
react-native run-android / ios
