### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by RobertArissen** [evollu/react-native-fcm#515]
Hi @evollu 

My iOS version works fine. But my android compile give a error:

```
/Users/robertarissen/Desktop/Dev/Apps/sponsorij/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingPackage.java:13: error: FIRMessagingPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class FIRMessagingPackage implements ReactPackage {
       ^
1 error
:react-native-fcm:compileReleaseJavaWithJavac FAILED
```

How can I fix this?
```
"react-native": "0.45.1",,
"react-native-fcm": "^8.0.0",
```

**Comment by dieunt** [comment]
I have the same problem with:
"react": "^16.0.0-alpha.12",
"react-native": "^0.45.1",
"react-native-fcm": "^8.0.0"

**Comment by MilosR** [comment]
It works with 7.5.1, (i got same error with 8.0.0), this combination works:

"react-native": "^0.46.1",
"react-native-fcm": "7.5.1",

**Comment by lfallet** [comment]
As per the readme:
> for RN < 0.47.0, use react-native-fcm@7.5.1

Therefore you should downgrade react-native-fcm to version 7.5.x or **upgrade react-native to version 0.47.x and keep react-native-fcm version 8.0.x**
