### ISSUE TITLE
Can't build on Xcode 8.2

### ISSUE THREAD

**Issue by pewh** [evollu/react-native-fcm#789]
Before openning an issue
1. Reproduce it with the example project in this repo.
2. If you can't receive iOS notification, make sure you can receive notification using quickstart-ios project provided by Firebase team

When openning an issue, please include following information for better support
1. What version of RN and react-native-fcm are you running? RN 0.52 & RNFCM 13.1.0
2. What device are you using? (e.g iOS9 emulator, Android 6 device)? iOS
3. Is your app running in foreground, background or not running?

Previously I can build, but I don't know since when it can't build again on current Xcode 8.2.

I get an error like this:
```
/Users/pewh/Documents/KLOP/node_modules/react-native-fcm/ios/RNFIRMessaging.m:196:13: error: unexpected '@' in program
        if (@available(iOS 11.0, *)) {
            ^
/Users/pewh/Documents/KLOP/node_modules/react-native-fcm/ios/RNFIRMessaging.m:197:44: error: no known class method for selector 'categoryWithIdentifier:actions:intentIdentifiers:hiddenPreviewsBodyPlaceholder:options:'
            return [UNNotificationCategory categoryWithIdentifier:identifier actions:actions intentIdentifiers:intentIdentifiers hiddenPreviewsBodyPlaceholder:hiddenPreviewsBodyPlaceholder options:options];
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/pewh/Documents/KLOP/node_modules/react-native-fcm/ios/RNFIRMessaging.m:211:118: error: use of undeclared identifier 'UNNotificationCategoryOptionHiddenPreviewsShowTitle'
                                                           @"UNNotificationCategoryOptionHiddenPreviewsShowTitle": @(UNNotificationCategoryOptionHiddenPreviewsShowTitle),
                                                                                                                     ^
/Users/pewh/Documents/KLOP/node_modules/react-native-fcm/ios/RNFIRMessaging.m:212:121: error: use of undeclared identifier 'UNNotificationCategoryOptionHiddenPreviewsShowSubtitle'
                                                           @"UNNotificationCategoryOptionHiddenPreviewsShowSubtitle": @(UNNotificationCategoryOptionHiddenPreviewsShowSubtitle),
                                                                                                                        ^
4 errors generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

**Comment by pewh** [comment]
I can rid the Xcode issue by swapping `if (@available(iOS 11.0, *)) ` into:
 `#if defined(__IPHONE_11_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >=  __IPHONE_11_0`.

But I can't fix issue on `@(UNNotificationCategoryOptionHiddenPreviewsShowTitle)`. It seems Xcode < 9 can't read asterisk symbol, and unfortunately my system is stuck on El Capitan, which is can't upgrade Xcode to higher version.

**Comment by evollu** [comment]
it is a utility available on Xcode 9. can you upgrade to that?

**Comment by pewh** [comment]
It seems that code only work on Xcode < 9. I get that code from https://stackoverflow.com/a/25903635/1163092

Better to seeing alternative that work seamlessly for Xcode 7, 8, and 9.

**Comment by pewh** [comment]
So for now my current Xcode only work on RNFCM < 1.12.x

**Comment by evollu** [comment]
yes. I'm making the change

**Comment by evollu** [comment]
fixed in v13.2.0

**Comment by ikhsanalatsary** [comment]
I still facing this issue.
![screen shot 2018-02-26 at 1 42 25 pm](https://user-images.githubusercontent.com/5897415/36656459-24eec0c2-1afb-11e8-9005-bd3188ae6990.png)
I tried in this repo https://github.com/ikhsanalatsary/project-rn/tree/feat-fcm

**Comment by evollu** [comment]
@ikhsanalatsary that is something newly introduced. I guess you have to upgrade xcode this time

**Comment by zxiest** [comment]
For a temporary fix and to be able to build, add the following to `RNFIRMessaging.m`:

```
const UNNotificationCategoryOptionHiddenPreviewsShowTitle = (1 << 2);
const UNNotificationCategoryOptionHiddenPreviewsShowSubtitle = (1 << 3);
```

**Comment by evollu** [comment]
@zxiest what does it mean? does it break iOS 11?

**Comment by ikhsanalatsary** [comment]
@evollu yeah, finally I use a new mac

**Comment by zxiest** [comment]
@evollu I was able to build by adding the lines above. Nothing is breaking for me.

**Comment by evollu** [comment]
@zxiest can you explain what it is doing? does it override system default value? sounds dangerous

**Comment by zxiest** [comment]
@evollu it's just a declaration that is missing in old headers. Nothing dangerous about it. It's setting the variables to 4 and 8.

**Comment by evollu** [comment]
@zxiest I can check to apply the change. do you have to stick with old xcode?
