### ISSUE TITLE
FAILURE: Build failed with version 15.0.0 / 14.0.0

### ISSUE THREAD

**Issue by rochapablo** [evollu/react-native-fcm#937]
I was working with `"react-native-fcm": "10.0.3"` and it was all building nicely, when I changed to `15.0.0/14.0.0` it stop to build giving me the follow error;

```
> Task :app:compileDebugJavaWithJavac
../android/app/src/main/java/com/theapp/MainFirebaseMessagingService.java:66: error: cannot access zzbfm
        if(remoteMessage.getFrom().startsWith("/topics/")) {
                        ^
  class file for com.google.android.gms.internal.zzbfm not found
../android/app/src/main/java/com/theapp/MainFirebaseMessagingService.java:88: error: no suitable method found for putExtra(String,RemoteMessage)
        i.putExtra("data", remoteMessage);
         ^
    method Intent.putExtra(String,boolean) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to boolean)
    method Intent.putExtra(String,byte) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to byte)
    method Intent.putExtra(String,char) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to char)
    method Intent.putExtra(String,short) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to short)
    method Intent.putExtra(String,int) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to int)
    method Intent.putExtra(String,long) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to long)
    method Intent.putExtra(String,float) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to float)
    method Intent.putExtra(String,double) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to double)
    method Intent.putExtra(String,String) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to String)
    method Intent.putExtra(String,CharSequence) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to CharSequence)
    method Intent.putExtra(String,Parcelable) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Parcelable)
    method Intent.putExtra(String,Parcelable[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Parcelable[])
    method Intent.putExtra(String,Serializable) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Serializable)
    method Intent.putExtra(String,boolean[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to boolean[])
    method Intent.putExtra(String,byte[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to byte[])
    method Intent.putExtra(String,short[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to short[])
    method Intent.putExtra(String,char[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to char[])
    method Intent.putExtra(String,int[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to int[])
    method Intent.putExtra(String,long[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to long[])
    method Intent.putExtra(String,float[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to float[])
    method Intent.putExtra(String,double[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to double[])
    method Intent.putExtra(String,String[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to String[])
    method Intent.putExtra(String,CharSequence[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to CharSequence[])
    method Intent.putExtra(String,Bundle) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Bundle)
Note: ../android/app/src/main/java/com/theapp/UnlockScreenActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

The only change was the version then `rm -rf node_modules` + `npm i` + `"run android"` and `v13.3.3` it's the only newest version that build.

"react-native": "^0.48.4",
"react-native-fcm": "15.0.0",

Could this error be related to the new version?

**Comment by evollu** [comment]
have you tried to upgrade your Firebase SDK to latest?

**Comment by rochapablo** [comment]
Not yet... I'm gonna try.

Closing for now.

**Comment by sanjayMantati** [comment]
how did you upgrade Firebase SDK ??
