### ISSUE TITLE
FIRApp undefined after upgrading to 2.1.0

### ISSUE THREAD

**Issue by tijs** [evollu/react-native-fcm#113]
When i upgrade this package to the latest 2.1.0 (from 2.0.3) i get an error that FIRApp is undefined in the Appdelegate.m file:

    [FIRApp configure];

I'm using xcode 8. Have not tried on xcode 7. When i revert back to 2.0.3 the issue is gone.

**Comment by antoinerousseau** [comment]
same for me when running `react-native run-ios`:

```
AppDelegate.m:39:4: error: use of undeclared identifier 'FIRApp'
  [FIRApp configure];
   ^
```

**Comment by tijs** [comment]
@antoinerousseau yeah that's indeed the exact error i get. are you also running xcode 8? i assume something is preventing @evollu from getting the same error...

**Comment by antoinerousseau** [comment]
Xcode 7.3

**Comment by evollu** [comment]
are you using cocoa pods?

**Comment by evollu** [comment]
i changed import in module from h file to framework, could that be the issue?

**Comment by tijs** [comment]
i am using cocoapods. what can i change to see if thats the issue?

**Comment by antoinerousseau** [comment]
yes i'm using cocoapods

**Comment by evollu** [comment]
i will try to create a demo project today 
can you give me screenshot of
your appdelegate.m
your pods folder

and have you tried clearing the project and rebuild?

**Comment by evollu** [comment]
try add @import Firebase in appdelegatr

**Comment by antoinerousseau** [comment]
my `AppDeletage.m`:

```objective-c
#import "AppDelegate.h"
#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

#import "RNFIRMessaging.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"tribeez"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [FIRApp configure];
  [Fabric with:@[[Crashlytics class]]];
  return YES;
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
  fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))handler
{
  [[NSNotificationCenter defaultCenter] postNotificationName:FCMNotificationReceived object:self userInfo:notification];
  handler(UIBackgroundFetchResultNewData);
}

@end
```

My `Pods` folder:

![capture d ecran 2016-09-21 14 49 01](https://cloud.githubusercontent.com/assets/160279/18711503/8f22b99a-800a-11e6-8574-c9ed9e3ef18a.png)

What do you mean clearing the project?

**Comment by antoinerousseau** [comment]
you can see all at https://github.com/antoinerousseau/tribeez/tree/master/ios

**Comment by jcharbo** [comment]
I'm having the same problem.  I made it work by changing `+@import Firebase;
 +@import FirebaseMessaging;` inside of ios/rnfirmessage.h to `#import "Firebase.h"`.  I don't know if this should be the fix but it worked for me.

**Comment by evollu** [comment]
it is no long @import Firebase in the code now. Can you get the latest? or I didn't release it?

**Comment by evollu** [comment]
check v2.1.1

**Comment by antoinerousseau** [comment]
my version had 
```
@import FirebaseInstanceID;
@import FirebaseMessaging;
```
and it failed with this.


Now I just tried to update to v2.2.0 and I get:

```
The following commands produced analyzer issues:
	Analyze RNFIRMesssaging.m
(1 command with analyzer issues)

The following build commands failed:
	Analyze RNFIRMesssaging.m
	CompileC /Users/antoine/Sites/tribeez/ios/build/Build/Intermediates/RNFIRMessaging.build/Debug-iphonesimulator/RNFIRMessaging.build/Objects-normal/x86_64/RNFIRMesssaging.o RNFIRMesssaging.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

**Comment by antoinerousseau** [comment]
above this error is a fatal one:
```
node_modules/react-native-fcm/ios/RNFIRMesssaging.m:8:9: fatal error: module 'UserNotifications' not found
@import UserNotifications;
 ~~~~~~~^~~~~~~~~~~~~~~~~
```

**Comment by antoinerousseau** [comment]
I'll try to upgrade Xcode from 7 to 8

**Comment by antoinerousseau** [comment]
just installed Xcode 8 and updated my `AppDelegage` according to latest `README`.
now I have a bunch of errors (cc @evollu):

```
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:28:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitMinute;
           ^~~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:31:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitSecond;
           ^~~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:34:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitDay;
           ^~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:37:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitMonth;
           ^~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:40:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitWeekOfYear;
           ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:43:12: warning: incompatible integer to pointer conversion returning 'NSUInteger'
      (aka 'unsigned long') from a function with result type 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *') [-Wint-conversion]
    return NSCalendarUnitYear;
           ^~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:63:31: warning: incompatible pointer to integer conversion assigning to 'NSCalendarUnit'
      (aka 'enum NSCalendarUnit') from 'NSCalendarUnit *' (aka 'enum NSCalendarUnit *'); dereference with * [-Wint-conversion]
  notification.repeatInterval = [RCTConvert NSCalendarUnit:details[@"repeat_interval"]];
                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                *(                                                     )
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:227:43: error: expected a type
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                                          ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:104:29: error: no visible @interface for 'FIRMessaging' declares the selector
      'setRemoteMessageDelegate:'
  [[FIRMessaging messaging] setRemoteMessageDelegate:self];
   ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:124:106: warning: unused parameter 'reject' [-Wunused-parameter]
RCT_EXPORT_METHOD(getInitialNotification:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject){
                                                                                                         ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:133:95: warning: unused parameter 'reject' [-Wunused-parameter]
RCT_EXPORT_METHOD(getFCMToken:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
                                                                                              ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:144:12: warning: 11 enumeration values not handled in switch: 'NSCalendarUnitEra',
      'NSCalendarUnitHour', 'NSWeekCalendarUnit'... [-Wswitch]
    switch(notif.repeatInterval){
           ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:138:114: warning: unused parameter 'reject' [-Wunused-parameter]
RCT_EXPORT_METHOD(getScheduledLocalNotifications:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
                                                                                                                 ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:186:28: warning: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead
      [-Wdeprecated-declarations]
  [_bridge.eventDispatcher sendDeviceEventWithName:@"FCMTokenRefreshed" body:[[FIRInstanceID instanceID] token]];
                           ^
In file included from /Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:5:
../../react-native/React/Base/RCTEventDispatcher.h:70:1: note: 'sendDeviceEventWithName:body:' has been explicitly marked deprecated here
- (void)sendDeviceEventWithName:(NSString *)name body:(id)body
^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:216:31: warning: unused parameter 'granted' [-Wunused-parameter]
     completionHandler:^(BOOL granted, NSError * _Nullable error) {
                              ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:216:60: warning: unused parameter 'error' [-Wunused-parameter]
     completionHandler:^(BOOL granted, NSError * _Nullable error) {
                                                           ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:228:96: error: no known instance method for selector 'appData'
  [_bridge.eventDispatcher sendDeviceEventWithName:FCMNotificationReceived body:[remoteMessage appData]];
                                                                                               ^~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:228:28: warning: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead
      [-Wdeprecated-declarations]
  [_bridge.eventDispatcher sendDeviceEventWithName:FCMNotificationReceived body:[remoteMessage appData]];
                           ^
In file included from /Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:5:
../../react-native/React/Base/RCTEventDispatcher.h:70:1: note: 'sendDeviceEventWithName:body:' has been explicitly marked deprecated here
- (void)sendDeviceEventWithName:(NSString *)name body:(id)body
^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:269:57: warning: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to
      parameter of type 'NSInteger' (aka 'long'); dereference with * [-Wint-conversion]
  [RCTSharedApplication() setApplicationIconBadgeNumber:number];
                                                        ^~~~~~
                                                        *
In module 'UIKit' imported from /Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMessaging.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:161:32: note:
      passing argument to parameter 'applicationIconBadgeNumber' here
@property(nonatomic) NSInteger applicationIconBadgeNumber;  // set to 0 to hide. default is 0. In iOS 8.0 and later, your application must register for user notifications us...
                               ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:272:99: warning: unused parameter 'reject' [-Wunused-parameter]
RCT_EXPORT_METHOD(getBadgeNumber: (RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
                                                                                                  ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:281:28: warning: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead
      [-Wdeprecated-declarations]
  [_bridge.eventDispatcher sendDeviceEventWithName:FCMNotificationReceived body:data];
                           ^
In file included from /Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:5:
../../react-native/React/Base/RCTEventDispatcher.h:70:1: note: 'sendDeviceEventWithName:body:' has been explicitly marked deprecated here
- (void)sendDeviceEventWithName:(NSString *)name body:(id)body
^
18 warnings and 3 errors generated.
```

...

```
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:227:43: error: expected a type
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                                          ^
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:104:29: error: no visible @interface for 'FIRMessaging' declares the selector
      'setRemoteMessageDelegate:'
  [[FIRMessaging messaging] setRemoteMessageDelegate:self];
   ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/antoine/Sites/tribeez/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:228:96: error: no known instance method for selector 'appData'
  [_bridge.eventDispatcher sendDeviceEventWithName:FCMNotificationReceived body:[remoteMessage appData]];
                                                                                               ^~~~~~~
```

**Comment by evollu** [comment]
@antoinerousseau 
```
[[FIRMessaging messaging] setRemoteMessageDelegate:self];
``` 
is introduced in latest firebase SDK. try update your pods

**Comment by antoinerousseau** [comment]
how do you clear your build?

**Comment by evollu** [comment]
i'll look at your repo and try to fix it @antoinerousseau

**Comment by evollu** [comment]
@antoinerousseau run pod update. you are still using 3.5.x firebase SDK

**Comment by evollu** [comment]
@tijs try latest version. I made a fix for your issue

**Comment by tijs** [comment]
@evollu thanks i will!

**Comment by antoinerousseau** [comment]
@evollu sure you can use it :)
thanks!

**Comment by antoinerousseau** [comment]
@evollu so running `pod update` indeed fixed this issue, and there is a little typo in the doc:
search for ` + + `, it should be a space (in "Shared steps">"Edit AppDelegate.m")

**Comment by tijs** [comment]
@evollu yup that seems to have fixed it. thanks a lot! (feel free to close it i guess)

**Comment by trathailoi** [comment]
help me :(
`/Volumes/Data Storage/Bizzon/project/up-mobile/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:227:43: error: expected a type
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                                          ^
/Volumes/Data Storage/Bizzon/project/up-mobile/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:104:29: error: no visible @interface for 'FIRMessaging' declares the selector 'setRemoteMessageDelegate:'
  [[FIRMessaging messaging] setRemoteMessageDelegate:self];
   ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/Data Storage/Bizzon/project/up-mobile/node_modules/react-native-fcm/ios/RNFIRMesssaging.m:228:96: error: no known instance method for selector 'appData'
  [_bridge.eventDispatcher sendDeviceEventWithName:FCMNotificationReceived body:[remoteMessage appData]];
                                                                                               ^~~~~~~
3 errors generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1`

**Comment by trathailoi** [comment]
> `_****_`

**Comment by bernatfortet** [comment]
@trathailoi I was having a similar issue in here https://github.com/evollu/react-native-fcm/issues/163 and I solved it. (yet I'm stuck in another place, now)

**Comment by Kalyani518** [comment]
I was having a similar issue
The following commands produced analyzer issues:
	Analyze RNFIRMessaging.m
(1 command with analyzer issues)

**Comment by timomeh** [comment]
Exactly the same error as @Kalyani518 

```
The following commands produced analyzer issues:

	Analyze RNFIRMessaging.m
(1 command with analyzer issues)
```

**Comment by evollu** [comment]
try update your pods?
looks like the firebase lib is not linked correctly

**Comment by timomeh** [comment]
I don't use pods. I linked it manually with the "Non Cocoapod approach" from the Docs. Is there anything special I should check for when manually linking firebase?

**Comment by evollu** [comment]
have you dragged those frameworks into the solution and referenced them?

**Comment by timomeh** [comment]
I removed all firebase libraries and added them again, just to be sure.

This is how I added them: I dragged the 4 Libraries from the Analytics Directory and the Messaging Directory into the Project Navigator Pane from xcode, respectively into the Frameworks Directory (with copy items if needed checked). This adds the *.framework files directly into `my-reactnative-project/ios` directory. I don't have a directory called `my-reactnative-project/ios/frameworks`.

If I look in Xcode at Targets > MyProject > Build Phases > Link Binary with Libraries, all 6 Frameworks are listed, also libRNFIRMessaging.a is at the end of the list.

Then I cleared the project (`CMD-Shift-K`), just to keep things clean after all those changes.

After that, I build the project inside xcode, just to test if it would build. This fails with `'FirebaseCode/FIRApp.h' file not found (RNFIRMessaging.h)`.

If I run `react-native run-ios`, it fails with:

```
The following commands produced analyzer issues:
	Analyze RNFIRMessaging.m
(1 command with analyzer issues)

The following build commands failed:
	CompileC build/Build/Intermediates/REDACTED.build/Debug-iphonesimulator/REDACTED.build/Objects-normal/x86_64/AppDelegate.o REDACTED/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I really appreciate your help.

**Comment by timomeh** [comment]
Additional info: I also linked it the module with `react-native link react-native-fcm`

**Comment by timomeh** [comment]
More info: Sometimes `react-native run-ios` also fails with

```
In file included from /Users/timomaemecke/Documents/dev/REDACTED/ios/REDACTED/AppDelegate.m:11:
/Users/timomaemecke/Documents/dev/REDACTED/ios/../node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: 'FirebaseCore/FIRApp.h' file not found
#import <FirebaseCore/FIRApp.h>
        ^
1 error generated.
```

(Sorry for spamming info's here, I'm just trying to give as much information as possible)

**Comment by evollu** [comment]
can you check framework search path of RNFIRMessaging project? I have $(PROJECT_DIR)/../../../ios there but wonder it includes the place you put your framework file

**Comment by timomeh** [comment]
Framework Search Path inside `node_modules/react-native-fcm/ios/RNFIRMessaging.xcodeproj/project.pbxproj` is

```
FRAMEWORK_SEARCH_PATHS = (
  "$(inherited)",
  "$(PROJECT_DIR)/../../../ios/**",
  "$(SRCROOT)/../../../node_modules/react-native-firestack/ios/**",
)
```

**Comment by timomeh** [comment]
I solved it somehow. I copied the framework files into `~/Documents/FirebaseSDK` and added this path to the `Any SDK` Section inside the Framework Search Paths of my project.

![image](https://cloud.githubusercontent.com/assets/4227520/25943300/bd55a69c-363f-11e7-8424-768ea22b2d74.png)

[react-native-fbsdk](https://github.com/facebook/react-native-fbsdk) does the same thing.

I don't think that's a very pretty solution, but the app builds, so I'm fine with it. 😅

**Comment by evollu** [comment]
it will break next time you install the package. like in CI?
so seems the issue is the path is not correctly set. can you verify that your SDK file is inside`$(PROJECT_DIR)/../../../ios/**`? try put these files in a subfolder of ios folder?

**Comment by timomeh** [comment]
I tried everything. Can verify the frameworks are there. We tried to build it on the machine of a colleague and it worked without problems, so that's our solution for now.

**Comment by evollu** [comment]
OK.
